function h(o){window.location.hash=o}function k(o){o.classList.add("flex","items-center","justify-center","bg-black","text-white","h-screen");let e=document.createElement("div");e.classList.add("flex-1","py-12","sm:py-16","lg:py-20"),o.appendChild(e);let l=document.createElement("div");l.classList.add("mx-auto","max-w-7xl","px-4","sm:px-6","lg:px-8"),e.appendChild(l);let a=document.createElement("div");a.classList.add("grid","grid-cols-1","gap-y-16","lg:grid-cols-2","lg:gap-x-8"),l.appendChild(a);let t=document.createElement("div");t.classList.add("lg:pr-8"),a.appendChild(t);let n=document.createElement("h1");n.classList.add("text-2xl","font-bold","tracking-tight","sm:text-5xl"),n.textContent="Hi, my name is",t.appendChild(n);let r=document.createElement("h1");r.classList.add("text-7xl","font-extrabold","text-white"),r.textContent="Andr\xE9 Marques",t.appendChild(r);let i=document.createElement("h1");i.classList.add("text-2xl","font-bold","tracking-tight","sm:text-5xl"),t.appendChild(i);let c=document.createElement("span");c.id="animate",i.appendChild(c);let d=document.createElement("div");d.classList.add("relative","h-72"),a.appendChild(d);let s=document.createElement("img");s.src="./assets/final-class.jpg",s.alt="Andr\xE9 Marques teaching a class at Code For all",s.classList.add("absolute","inset-0","h-full","w-full","object-contain","rounded-lg"),s.width=1200,s.height=900,s.style.aspectRatio="1200 / 900",s.style.objectFit="cover",d.appendChild(s),p(o);let u=document.createElement("button");u.classList.add("mt-8","px-4","py-2","text-lg","font-semibold","text-white","bg-red-500","rounded-lg","hover:bg-red-700","focus:outline-none","focus:ring-2","focus:ring-red-500","focus:ring-offset-2","focus:ring-offset-black"),u.textContent="Contact me",u.addEventListener("click",()=>{h("/contact")}),l.appendChild(u)}function p(o){let e=o.querySelector("#animate");e.classList.add("text-red-500"),e.style.fontWeight="bold",e.style.borderRight="2px solid #fff",e.style.animation="blinkingCursor 0.7s step-end infinite",e.style.whiteSpace="nowrap",e.style.overflow="hidden",e.style.width="fit-content";let l=document.createElement("style");l.innerHTML=m(),o.appendChild(l);let a=["FullStack Developer","Teacher","JavaScript Developer","Java Developer","React.js Developer","Node.js Developer","Mentor","Dancer","Speaker"],t=0,n=0,r=a[n],i="";function c(){t<r.length?(i+=r[t],e.innerHTML=i,t++,setTimeout(c,200)):setTimeout(d,1e3)}function d(){t>0?(i=r.substring(0,t-1),e.innerHTML=i,t--,setTimeout(d,200)):(n++,n>=a.length&&(n=0),r=a[n],setTimeout(c,500))}c()}function m(){return`
      @keyframes blinkingCursor {
        from, to {
          border-color: transparent;
        }
        50% {
          border-color: #fff;
        }
      }
    `}export{k as render};
